### ISSUE TITLE
wikipedia_redirect contains too many redirects

### ISSUE THREAD

**Issue by lonvia** [osm-search/wikipedia-wikidata#44]
The `wikipedia_redirect` table currently contains all redirects that wikipedia has. It should be limited to redirects to pages that are in `wikipedia_article`.

**Comment by mtmail** [comment]
Who many redirects do you see? The logic is

```sql
CREATE TABLE wikipedia_redirect
      AS
      SELECT wikipedia_redirect_full.*
      FROM wikipedia_redirect_full
      RIGHT OUTER JOIN wikipedia_article
                   ON (wikipedia_redirect_full.language = wikipedia_article.language
                       AND
                       wikipedia_redirect_full.to_title = wikipedia_article.title)
```

`wikpedia_redirect_full` is 37,498,865
`wikipedia_redirect` is 13,429,368
`wikipedia_article` is 9,008,457
