### ISSUE TITLE
Duplicate entries in wikimedia_importance CSV

### ISSUE THREAD

**Issue by lonvia** [osm-search/wikipedia-wikidata#52]
The wikimedia_importance.csv does have duplicates wrt (language, title). This is not allowed because we have a uniqueness constraint in the database. They do differ in their wikidata entry, which is really odd. Example:

```
en,01_Distribution,0.3191129613920406,Q1554656
en,01_Distribution,0.6355219495742352,Q19616
```
The 'Q19616' is for Italian TV station RAI, so looks rather wrong.

**Comment by mtmail** [comment]
The second line (Q19616) is a redirect and the title is the `from_title`.  There's another 20 entries pointing to Q19616 like "Rai_(broadcaster)", "Radio_Audizioni_Italiane", "Radiotelevisione_italiana" etc.

The difference is that this redirect https://en.wikipedia.org/w/index.php?title=01_Distribution&redirect=no also has a wikidata entry Q1554656
while the others, e.g.
https://en.wikipedia.org/w/index.php?title=Radiotelevisione_italiana&redirect=no don't.

Wouldn't OSM places maybe reference such redirect's wikidata id, too? That goes into the question what a unique thing in wikipedia is. We could remove those ids. Or create a mapping (separate file). Or concentate them.

**Comment by lonvia** [comment]
The Italian wikipedia has an [article  for 01 Distribution](https://it.wikipedia.org/wiki/01_Distribution). That's why there is an extra wikidata item here. IMHO the link to the unredirected article Q1554656 would be the right information to have. So basically: prefer (language, title) from the `article` table over those from the `redirect` table`.

BTW there is still a problem with having different importance values for the same wikidata entry:

```
nominatim=# select * from wikimedia_importance where wikidata = 'Q1554656';
 language |      title       |     importance      | wikidata 
----------+------------------+---------------------+----------
 en       | 01_Distribution  |  0.3191129613920406 | Q1554656
 fr       | 01_Distribution  | 0.24288991347934977 | Q1554656
 he       | 01_Distribution  | 0.19299670588458645 | Q1554656
 it       | 01_Distribution  |  0.4527108288828962 | Q1554656
 it       | 01_Distribuzione |  0.4527108288828962 | Q1554656
(5 rows)
```

I presume that that is also a result of the redirects?
