### ISSUE TITLE
Practical use

### ISSUE THREAD

**Issue by zaa76** [osm-search/wikipedia-wikidata#79]
Hello!

Using this repository, I processed melons from Wiki
I received, as you described, four files:
wikimedia_importance.csv.gz
wikipedia_importance.sql.gz
wikipedia_article.csv.gz
wikipedia_redirect.csv.gz

I don't understand how to continue using these files with Nominatim

it only requires the wikimedia-importance.sql.gz file

My version Nominatim 4.3.0

**Comment by mtmail** [comment]
You can delete the *.csv.gz files, those are for different versions of Nominatim and contain the same data, just formatted differently.

You can import the *.sql.gz file with
https://nominatim.org/release-docs/latest/admin/Import/#wikipediawikidata-rankings
