### ISSUE TITLE
`unpigz -c`  vs. ( gzip -dc | zcat )  speed

### ISSUE THREAD

**Issue by ImreSamu** [osm-search/wikipedia-wikidata#9]
imho :
*  the pigz based uncompression  ( `unpigz -c` )  is faster than the [current](https://github.com/osm-search/wikipedia-wikidata/search?q=%22gzip+-dc%22) `gzip -dc` method.
* It is worth rechecking  .. 

see:
* https://unix.stackexchange.com/questions/363644/fastest-and-most-efficient-way-to-get-number-of-records-lines-in-a-gzip-compre/363739#363739

**Comment by mtmail** [comment]
Nice, first time I hear about this tool.

The stackexchange answer talks about a 2010 laptop. I ran it on my "in the cloud" test server with 9GB wikipedia files:

```
time zcat enwiki-latest-*.gz | wc -l
real	9m49.262s

# second time to account for disk cache
time zcat enwiki-latest-*.gz | wc -l
real	8m3.388s

time unpigz -c enwiki-latest-*.gz | wc -l
real	4m19.370s
```

Total data is 39GB compressed so the savings would be around 4.3*5min = 21.5min. Not bad for replacing a couple of lines!

**Comment by darkshredder** [comment]
I would like to work on this issue if it is still available to work on.

**Comment by ImreSamu** [comment]
> I would like to work on this issue if it is still available to work on.

I will pass the decision to @mtmail  ..   


some comment:

1.)
probably a [basic parallelization (`&` and `wait`) ](https://unix.stackexchange.com/a/417802)  also can be added easily ..

```
unpigz -c wikidatawiki-latest-geo_tags.sql.gz          | mysql2pgsqlcmd | psqlcmd  &
unpigz -c wikidatawiki-latest-page.sql.gz              | mysql2pgsqlcmd | psqlcmd  &
unpigz -c wikidatawiki-latest-wb_items_per_site.sql.gz | mysql2pgsqlcmd | psqlcmd  &
wait
```

2.)
I am still examining the `pigz-ng`   ( pigz + brand new  [zlib-ng](https://github.com/zlib-ng/zlib-ng/releases) )   
* PRO:  Based on this benchmark : https://github.com/zlib-ng/pigzbench   ... it is  +17% faster   (  `pigz-ng` ( 361mb/s )  vs `pigz-Sys` (306mb/s )  )
* CON:  need a special containerized [ETL workflow](https://en.wikipedia.org/wiki/Extract,_transform,_load)   ( with an optimized Docker image .. )

**Comment by mtmail** [comment]
@darkshredder I'd like to first move the initial download phase into a separate script because there's 4 download related ideas open. I have it half-ready so it would possibly duplicate work. After https://github.com/osm-search/wikipedia-wikidata/issues/5 (or worse if we have to write a replacement ourselves) the database schema will change a bit but then there will be more tasks available. I'll make an effort to label then 'help wanted', I think that's the label the Nominatim project uses.

**Comment by darkshredder** [comment]
Sure, no problem
